In [1]:
import numpy as np
print(np.version.version)

1.16.4


In [5]:
a = np.random.random((2,3,5))
print(a)

[[[0.80738193 0.89709179 0.02277691 0.42239321 0.76914464]
  [0.12355605 0.89098733 0.29143361 0.54564215 0.08480286]
  [0.13475012 0.09207052 0.87578196 0.34230927 0.73428893]]

 [[0.62352271 0.54704305 0.42919128 0.69395507 0.60906964]
  [0.21388056 0.12570651 0.26072387 0.44149425 0.90266493]
  [0.45542534 0.38964264 0.11875719 0.49987229 0.64388293]]]


In [7]:
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
